name: MIOS
url: 'mioscode.github.io'
description: 'MIOS Code and Thinks'

exclude: [Gemfile, Gemfile.lock, README.md]
markdown: kramdown

author: 'MIOS'
disqus_shortname: MIOS
google_analytics: UA-141787615-1

gems:
  # https://help.github.com/articles/atom-rss-feeds-for-github-pages/
  - jekyll-gist
  - jekyll-sitemap

sass:
    sass_dir: _sass
    style: :compressed
